/**
 * API types and hooks.
 *
 * In production, this file is auto-generated by Orval from the FastAPI OpenAPI schema.
 * Run `bun run generate-api` with the backend running to regenerate.
 */

import {
  useSuspenseQuery,
  useMutation,
  useQueryClient,
  type UseSuspenseQueryOptions,
} from "@tanstack/react-query";

// ─── Response Types ────────────────────────────────────────────

export interface HealthOut {
  status: string;
  authenticated: boolean;
  events_stored: number;
}

export interface AuthStatusOut {
  authenticated: boolean;
  token_expired: boolean | null;
}

export interface LogoutOut {
  status: string;
}

export interface EventOut {
  id: string;
  received_at: string;
  data_type: string;
  event_type: string;
  user_id: string | null;
  timestamp: string | null;
  data: Record<string, unknown> | null;
}

export interface EventListOut {
  count: number;
  total_stored: number;
  events: EventOut[];
}

export interface ClearEventsOut {
  status: string;
  count: number;
}

export interface SubscriptionOut {
  id: string;
  callback_url: string | null;
  data_type: string | null;
  event_type: string | null;
  expiration_time: string | null;
}

export interface SubscriptionDeleteOut {
  status: string;
  id: string;
}

export interface CreateSubscriptionBody {
  callback_url: string;
  verification_token: string;
  data_type: string;
  event_type?: string;
}

// ─── Fetcher ───────────────────────────────────────────────────

async function apiFetch<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, {
    ...init,
    headers: { "Content-Type": "application/json", ...init?.headers },
  });
  if (!res.ok) throw new Error(`API ${res.status}: ${await res.text()}`);
  return res.json();
}

// ─── Query Keys ────────────────────────────────────────────────

export const queryKeys = {
  health: ["health"] as const,
  authStatus: ["authStatus"] as const,
  events: (params?: { limit?: number; data_type?: string }) =>
    ["events", params] as const,
  subscriptions: ["subscriptions"] as const,
};

// ─── Suspense Query Hooks ──────────────────────────────────────

export function useGetHealthSuspense(
  options?: Partial<UseSuspenseQueryOptions<HealthOut>>,
) {
  return useSuspenseQuery({
    queryKey: queryKeys.health,
    queryFn: () => apiFetch<HealthOut>("/api/health"),
    ...options,
  });
}

export function useGetAuthStatusSuspense(
  options?: Partial<UseSuspenseQueryOptions<AuthStatusOut>>,
) {
  return useSuspenseQuery({
    queryKey: queryKeys.authStatus,
    queryFn: () => apiFetch<AuthStatusOut>("/api/auth/status"),
    ...options,
  });
}

export function useListEventsSuspense(
  params?: { limit?: number; data_type?: string },
  options?: Partial<UseSuspenseQueryOptions<EventListOut>>,
) {
  const search = new URLSearchParams();
  if (params?.limit) search.set("limit", String(params.limit));
  if (params?.data_type) search.set("data_type", params.data_type);
  const qs = search.toString();
  return useSuspenseQuery({
    queryKey: queryKeys.events(params),
    queryFn: () => apiFetch<EventListOut>(`/api/events${qs ? `?${qs}` : ""}`),
    ...options,
  });
}

export function useListSubscriptionsSuspense(
  options?: Partial<UseSuspenseQueryOptions<SubscriptionOut[]>>,
) {
  return useSuspenseQuery({
    queryKey: queryKeys.subscriptions,
    queryFn: () => apiFetch<SubscriptionOut[]>("/api/subscriptions"),
    ...options,
  });
}

// ─── Mutation Hooks ────────────────────────────────────────────

export function useLogout() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: () => apiFetch<LogoutOut>("/api/auth/logout", { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: queryKeys.authStatus }),
  });
}

export function useClearEvents() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: () => apiFetch<ClearEventsOut>("/api/events", { method: "DELETE" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["events"] }),
  });
}

export function useCreateSubscription() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateSubscriptionBody) =>
      apiFetch<SubscriptionOut>("/api/subscriptions", {
        method: "POST",
        body: JSON.stringify(data),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: queryKeys.subscriptions }),
  });
}

export function useDeleteSubscription() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      apiFetch<SubscriptionDeleteOut>(`/api/subscriptions/${id}`, {
        method: "DELETE",
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: queryKeys.subscriptions }),
  });
}
